sudo: required
services:
  - docker

before_install:
  - docker image build -t mwiesbau/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run -e CI=true mwiesbau/react-test npm test -- --coverage

after_success:
  - docker image build -t mwiesbau/complex-client ./client
  - docker image build -t mwiesbau/complex-nginx ./nginx
  - docker image build -t mwiesbau/complex-server ./server
  - docker image build -t mwiesbau/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u $"DOCKER_ID" --password-stdin
  - docker image push mwiesbau/complex-client
  - docker image push mwiesbau/complex-nginx
  - docker image push mwiesbau/complex-server
  - docker image push mwiesbau/complex-worker